export const SPORT_DATA = [
  {
    sportingCode: 'Athletics',
    videos: [
      {
        id: 1,
        title: `Men's 100m final`,
        url: 'https://www.youtube.com/watch?v=zMFb8Y2QLPc',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 2,
        title: `Women's 100m Heat`,
        url: 'https://www.youtube.com/watch?v=XqwPBhOaa6A',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 3,
        title: `Men's 200m heat`,
        url: 'https://www.youtube.com/watch?v=55v4Jv6BBA0',
        broadcaster: 'CNBC',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 4,
        title: `Men's 5000`,
        url: 'https:/www.youtube.com/watch?v=zMFb8Y2QLPc',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 5,
        title: `Women's 800m `,
        url: 'https://www.youtube.com/watch?v=3zO1WoQKHlA',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
    ],
  },
  {
    sportingCode: 'Winter ❄️',
    videos: [
      {
        id: 10,
        title: 'Opening Ceremony',
        url: 'https://www.youtube.com/watch?v=NUs0iL5QOVI',
        broadcaster: 'CNBC',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 11,
        title: 'Figure Skating',
        url: 'https://www.youtube.com/watch?v=_7C1ZIMnNeQ',
        broadcaster: 'CNBC',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 12,
        title: 'Alpine Skiing Final',
        url: 'https://www.youtube.com/watch?v=Z8V6sdT89rA',
        broadcaster: 'CNBC',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 13,
        title: 'Ice Hockey final',
        url: 'https://www.youtube.com/watch?v=8ZYHKP9fflI',
        broadcaster: 'Sky Sport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 14,
        title: 'FreeStyle Skiing',
        url: 'https://www.youtube.com/watch?v=WSl1cVCpBFs',
        broadcaster: 'Sky Sport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 15,
        title: `Speed Skating Women's`,
        url: 'https://www.youtube.com/watch?v=KCf_VvVzoLw',
        broadcaster: 'Sky Sport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 16,
        title: 'Curling',
        url: 'https://www.youtube.com/watch?v=AVatarevWn8',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 17,
        title: 'Skeleton Heats',
        url: 'https://www.youtube.com/watch?v=KN-VWPJrHIc',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
    ],
  },

  {
    sportingCode: 'Basketball',
    videos: [
      {
        id: 23,
        title: `Men's Final`,
        url: 'https://www.youtube.com/watch?v=r-7rIun3t9M',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 24,
        title: 'Japan vs Slovenia',
        url: 'https://www.youtube.com/watch?v=WZRpXc6ksEw',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 25,
        title: 'USA vs Spain',
        url: 'https://www.youtube.com/watch?v=vsFMfrxq2eM',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 26,
        title: 'Nigeria vs USA',
        url: 'https://www.youtube.com/watch?v=N9KbNFdvM3g',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 27,
        title: `Women's Final`,
        url: 'https://www.youtube.com/watch?v=B-7WRKycjWk',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
    ],
  },
  {
    sportingCode: 'Football',
    videos: [
      {
        id: 30,
        title: `Women's gold Final`,
        url: 'https://www.youtube.com/watch?v=F7IE7vB8484',
        broadcaster: 'Bien',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 31,
        title: `Men's Goal Final`,
        url: 'https://www.youtube.com/watch?v=G6pYYaEsnxg',
        broadcaster: 'Bien',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 32,
        title: 'Ivory Coast Vs Spain',
        url: 'https://www.youtube.com/watch?v=TKK1jX7vQRI',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 33,
        title: 'Mexico vs France ',
        url: 'https://www.youtube.com/watch?v=vqGkQyb6IF4',
        broadcaster: 'Bien',
        comments: ['Hello World ', 'These athletes are talented'],
      },
      {
        id: 34,
        title: 'Mexico vs Japan Bronze final',
        url: 'https://www.youtube.com/watch?v=GYD3aVQ2G_Y',
        broadcaster: 'SuperSport',
        comments: ['Hello World ', 'These athletes are talented'],
      },
    ],
  },
];
